//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace turbemblog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtiketMakale
    {
        public int id { get; set; }
        public Nullable<int> MakaleId { get; set; }
        public Nullable<int> EtiketId { get; set; }
    
        public virtual Etiket Etiket { get; set; }
        public virtual Makale Makale { get; set; }
    }
}
